server:
  port: 2930

spring:
  application:
    name: config-server


  cloud:
    #git 相关配置
    config:
      server:
        git:
          uri: https://github.com/lee-xs/SpringCloudConfig/
          search-paths: response
          #username:
          #password:
      label: master

  #spring cloud bus相关配置
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:2922/eureka


